version: '2'
services:
  local-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    network_mode: bridge
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=job